### ISSUE TITLE
Extra annotation on author for package.json

### ISSUE THREAD

**Issue by schererja** [code-biscuits/json-biscuits#2]
A freshly created package.json from npm init with the author filled in shows an annotation of author.
Running on the following:
1. Windows 10
2. VSCode 1.50.1
3. json-biscuits 0.0.5
4. html-biscuits uninstalled
5. js/ts biscuits uninstalled

![image](https://user-images.githubusercontent.com/8645717/96187297-609a2c80-0f02-11eb-8130-2fc5c6e06315.png)

**Comment by schererja** [comment]
This might be interesting to note, if I move the fields above the scripts object, it no longer has the annotation.
![image](https://user-images.githubusercontent.com/8645717/96197209-fa6bd480-0f16-11eb-9be2-9fba421b9044.png)

**Comment by cmgriffing** [comment]
Thanks again for this report. I am planning on deprecating JSON Biscuits since we now have it working within Assorted Biscuits which handles multiple languages now.
That extension also fixes this issue.

https://marketplace.visualstudio.com/items?itemName=CodeBiscuits.assorted-biscuits

Due to differences in how they are handled in the extensions, HTML, JS/TS, and CSS Biscuits will still be their own plugins.
